{
  "formatVersion": "1.1",
  "component": {
    "group": "com.qncube.docbuider",
    "module": "docBuiderPlugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "docBuiderPlugin-1.0.jar",
          "url": "docBuiderPlugin-1.0.jar",
          "size": 17156,
          "sha512": "035705137d4f448932c6530701855a0957c20e7988559376d6fe1042600c81a6f62eed0d436d817b229dcf85eb70949146411d9d779510f34c4e53d72cdaf0fa",
          "sha256": "19df7b4aaf280aa5dc8f29c24fbb8756b9360006fc3a358b16793d108a3dc69a",
          "sha1": "c3f7b3fbb82dfe55ce328676bbf9c27005da1318",
          "md5": "2c2a9b91d94626bb87e538bb1b3d6a8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.76"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "docBuiderPlugin-1.0.jar",
          "url": "docBuiderPlugin-1.0.jar",
          "size": 17156,
          "sha512": "035705137d4f448932c6530701855a0957c20e7988559376d6fe1042600c81a6f62eed0d436d817b229dcf85eb70949146411d9d779510f34c4e53d72cdaf0fa",
          "sha256": "19df7b4aaf280aa5dc8f29c24fbb8756b9360006fc3a358b16793d108a3dc69a",
          "sha1": "c3f7b3fbb82dfe55ce328676bbf9c27005da1318",
          "md5": "2c2a9b91d94626bb87e538bb1b3d6a8e"
        }
      ]
    }
  ]
}
