{
  "formatVersion": "1.1",
  "component": {
    "group": "com.qncube.docbuider",
    "module": "docBuiderPlugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "docBuiderPlugin-1.0.jar",
          "url": "docBuiderPlugin-1.0.jar",
          "size": 17305,
          "sha512": "d0bd82cdda76b9d9ddb26b0140627f906bdfc630b2b91e17766058848d205fa6ca199a4f436520866ef93d57ea6be83c0c02cd3c9c5e04f6207a26fbcc2531d6",
          "sha256": "0bf15f8e05ff6593bc9a879c1cd22b73ce8f1245d2ffa5c5b6289ed67ef86e1c",
          "sha1": "b44901dfe880c97aa9808d3f2d4fc6448ea65da5",
          "md5": "ed4a46f12083337a8dd13c2e60b0d6d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.76"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "docBuiderPlugin-1.0.jar",
          "url": "docBuiderPlugin-1.0.jar",
          "size": 17305,
          "sha512": "d0bd82cdda76b9d9ddb26b0140627f906bdfc630b2b91e17766058848d205fa6ca199a4f436520866ef93d57ea6be83c0c02cd3c9c5e04f6207a26fbcc2531d6",
          "sha256": "0bf15f8e05ff6593bc9a879c1cd22b73ce8f1245d2ffa5c5b6289ed67ef86e1c",
          "sha1": "b44901dfe880c97aa9808d3f2d4fc6448ea65da5",
          "md5": "ed4a46f12083337a8dd13c2e60b0d6d1"
        }
      ]
    }
  ]
}
