{
  "formatVersion": "1.1",
  "component": {
    "group": "com.qncube.docbuider",
    "module": "docBuiderPlugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "docBuiderPlugin-1.0.jar",
          "url": "docBuiderPlugin-1.0.jar",
          "size": 17226,
          "sha512": "1aab607bcdb108e0d00405460ca77e83e0368708b2da2ce6a0b3fd02ff768f7ca81cd8b834e9364d225eef4a7d400e0409ca384b5800fa66a125a333cd36c7dc",
          "sha256": "c94bf10d769fad33b9840aa40d3c39dc6d029015ab1511a452dab8b553a5431d",
          "sha1": "233610569ad1e8208467b8c4291bc964a0fe3069",
          "md5": "43d49193c19fdd706b24c0d31ddeffb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.76"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "docBuiderPlugin-1.0.jar",
          "url": "docBuiderPlugin-1.0.jar",
          "size": 17226,
          "sha512": "1aab607bcdb108e0d00405460ca77e83e0368708b2da2ce6a0b3fd02ff768f7ca81cd8b834e9364d225eef4a7d400e0409ca384b5800fa66a125a333cd36c7dc",
          "sha256": "c94bf10d769fad33b9840aa40d3c39dc6d029015ab1511a452dab8b553a5431d",
          "sha1": "233610569ad1e8208467b8c4291bc964a0fe3069",
          "md5": "43d49193c19fdd706b24c0d31ddeffb2"
        }
      ]
    }
  ]
}
